INSERT INTO candidate (
  candidate_id,
  name,
  age,
  email,
  password_hash,
  current_position,
  location,
  visa_status,
  experience_years,
  salary_expectation,
  availability_date,
  skills_text,
  awards_text,
  certifications_text,
  projects_text,
  previous_positions,
  education
) VALUES
(
  '753b511f-32c2-56a1-94d6-b6984a4d49eb',
  'Kai Patel',
  28,
  'kai.patel@example.com',
  '$2a$10$exampleKaiPatel',
  'Senior Backend Engineer',
  'Toronto, CA',
  'TN eligible',
  9.0,
  185000,
  CURRENT_DATE + INTERVAL '14 days',
  'Go, GraphQL, PostgreSQL, Kafka, Distributed systems',
  'Recognized for Senior Backend Engineer excellence',
  'Certified Senior Backend Engineer',
  'Led payments rewrite for 5M users; built event-driven notification service',
  '[{"title":"Backend Engineer","org":"Northwind Systems","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"University of Waterloo","graduation_year":2012}]'
),
(
  '40273216-4461-5f49-bea8-df660a1bf668',
  'Kai Rhodes',
  29,
  'kai.rhodes@example.com',
  '$2a$10$exampleKaiRhodes',
  'Staff Frontend Engineer',
  'Vancouver, CA',
  'Canadian PR',
  8.5,
  185000,
  CURRENT_DATE + INTERVAL '21 days',
  'React, TypeScript, Next.js, GraphQL, Design Systems',
  NULL,
  NULL,
  'Scaled design system adoption across 8 squads; implemented SSR streaming UI',
  '[{"title":"Frontend Engineer","org":"Helios Labs","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Software Engineering","school":"McGill University","graduation_year":2013}]'
),
(
  'fa76282a-1c83-5fa9-ba5a-54e0aa22fbd1',
  'Kai Nakamura',
  30,
  'kai.nakamura@example.com',
  '$2a$10$exampleKaiNakamura',
  'Machine Learning Engineer',
  'Montreal, CA',
  'Open to LMIA / O-1',
  8.0,
  210000,
  CURRENT_DATE + INTERVAL '30 days',
  'Python, PyTorch, LLMOps, Feature Stores, Airflow',
  NULL,
  NULL,
  'Launched multilingual retrieval system; built realtime experimentation platform',
  '[{"title":"Data Scientist","org":"Nimbus AI","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"MSc Applied Math","school":"University of Toronto","graduation_year":2014}]'
),
(
  'b8b63cbf-0773-563d-a57a-c170362827c8',
  'Kai Okafor',
  31,
  'kai.okafor@example.com',
  '$2a$10$exampleKaiOkafor',
  'Platform Engineer',
  'Calgary, CA',
  'US Citizen',
  10.0,
  225000,
  CURRENT_DATE + INTERVAL '45 days',
  'Rust, Kubernetes, Terraform, AWS, Observability',
  NULL,
  'Certified Platform Engineer',
  'Designed multi-region Kubernetes platform; reduced infra spend 18%',
  '[{"title":"Site Reliability Engineer","org":"Cloudforge","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Electrical Engineering","school":"Georgia Tech","graduation_year":2015}]'
),
(
  '10628f51-f4ea-5667-93ef-7f7b10d10d60',
  'Kai Hernandez',
  32,
  'kai.hernandez@example.com',
  '$2a$10$exampleKaiHernandez',
  'Data Platform Engineer',
  'Ottawa, CA',
  'Canadian PR, TN ready',
  8.5,
  175000,
  CURRENT_DATE + INTERVAL '60 days',
  'Scala, Spark, Delta Lake, dbt, Snowflake',
  'Recognized for Data Platform Engineer excellence',
  NULL,
  'Migration to lakehouse architecture; built governance catalog',
  '[{"title":"Data Engineer","org":"Aurora Analytics","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Information Systems","school":"UBC","graduation_year":2016}]'
),
(
  'fe212d00-40cc-5ef3-97e2-d268cbf139b3',
  'Kai Liu',
  33,
  'kai.liu@example.com',
  '$2a$10$exampleKaiLiu',
  'Security Engineer',
  'Halifax, CA',
  'US Green Card',
  10.0,
  195000,
  CURRENT_DATE + INTERVAL '75 days',
  'AppSec, Threat Modeling, Node.js, Python, AWS',
  NULL,
  NULL,
  'Implemented SDL program; automated dependency scanning for 400 repos',
  '[{"title":"Security Analyst","org":"ShieldWorks","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Cybersecurity","school":"Carnegie Mellon","graduation_year":2017}]'
),
(
  '8bccbca2-eb0a-5a97-ad73-362f42bc7b9f',
  'Aria Patel',
  34,
  'aria.patel@example.com',
  '$2a$10$exampleAriaPatel',
  'Product Designer',
  'Winnipeg, CA',
  'UK Skilled Worker',
  6.0,
  145000,
  CURRENT_DATE + INTERVAL '90 days',
  'Figma, Prototyping, Motion, Accessibility, Research',
  NULL,
  'Certified Product Designer',
  'Led end-to-end redesign of telehealth onboarding + design tokens library',
  '[{"title":"UX Designer","org":"Aether Health","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BA Interaction Design","school":"Goldsmiths","graduation_year":2018}]'
),
(
  'cdcf9da8-88e8-57fc-b24d-abb06572a1b5',
  'Aria Rhodes',
  35,
  'aria.rhodes@example.com',
  '$2a$10$exampleAriaRhodes',
  'Full Stack Engineer',
  'Victoria, CA',
  'Canadian Citizen',
  7.5,
  180000,
  CURRENT_DATE + INTERVAL '105 days',
  'Node.js, React, GraphQL, PostgreSQL, Tailwind',
  NULL,
  NULL,
  'Shipped multi-tenant analytics platform; maintained component library',
  '[{"title":"Software Engineer","org":"Vector Labs","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BASc Computer Engineering","school":"University of Toronto","graduation_year":2019}]'
),
(
  '089e783c-49ae-5645-aa16-d2fadb63edd5',
  'Aria Nakamura',
  36,
  'aria.nakamura@example.com',
  '$2a$10$exampleAriaNakamura',
  'Mobile Engineer',
  'Edmonton, CA',
  'Australian PR',
  9.0,
  172000,
  CURRENT_DATE + INTERVAL '120 days',
  'React Native, Swift, Kotlin, GraphQL, CI/CD',
  'Recognized for Mobile Engineer excellence',
  NULL,
  'Built offline-first field app; introduced modular monorepo',
  '[{"title":"Mobile Developer","org":"Southern Apps","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"UNSW","graduation_year":2012}]'
),
(
  '92a9b05b-b09d-5157-923b-39775fed7b35',
  'Aria Okafor',
  37,
  'aria.okafor@example.com',
  '$2a$10$exampleAriaOkafor',
  'DevRel Engineer',
  'Remote - Canada',
  'EU Blue Card',
  8.0,
  165000,
  CURRENT_DATE + INTERVAL '14 days',
  'Typescript, Docs-as-Code, Workshops, Content Strategy',
  NULL,
  'Certified DevRel Engineer',
  'Grew developer community 3x; launched SDK reference apps',
  '[{"title":"Developer Advocate","org":"Polaris Cloud","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"Trinity College Dublin","graduation_year":2013}]'
),
(
  '9f4ae982-d124-5b92-b255-7e0900465d8b',
  'Aria Hernandez',
  28,
  'aria.hernandez@example.com',
  '$2a$10$exampleAriaHernandez',
  'AI Product Manager',
  'Seattle, WA',
  'US Citizen',
  9.5,
  210000,
  CURRENT_DATE + INTERVAL '21 days',
  'Roadmapping, Experiment Design, SQL, Python, Prompt Engineering',
  NULL,
  NULL,
  'Launched LLM-powered support agent reducing backlog 40%',
  '[{"title":"Product Manager","org":"Signal North","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"MBA","school":"MIT Sloan","graduation_year":2014}]'
),
(
  '14cf2ac3-27c7-56ac-8e53-6df2b5a0d2e1',
  'Aria Liu',
  29,
  'aria.liu@example.com',
  '$2a$10$exampleAriaLiu',
  'Senior Backend Engineer',
  'Austin, TX',
  'TN eligible',
  10.0,
  200000,
  CURRENT_DATE + INTERVAL '30 days',
  'Go, GraphQL, PostgreSQL, Kafka, Distributed systems',
  NULL,
  NULL,
  'Led payments rewrite for 5M users; built event-driven notification service',
  '[{"title":"Backend Engineer","org":"Northwind Systems","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"University of Waterloo","graduation_year":2015}]'
),
(
  'd0509444-6784-57a3-9dd9-0677414eae03',
  'Mason Patel',
  30,
  'mason.patel@example.com',
  '$2a$10$exampleMasonPatel',
  'Staff Frontend Engineer',
  'New York, NY',
  'Canadian PR',
  8.0,
  180000,
  CURRENT_DATE + INTERVAL '45 days',
  'React, TypeScript, Next.js, GraphQL, Design Systems',
  'Recognized for Staff Frontend Engineer excellence',
  'Certified Staff Frontend Engineer',
  'Scaled design system adoption across 8 squads; implemented SSR streaming UI',
  '[{"title":"Frontend Engineer","org":"Helios Labs","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Software Engineering","school":"McGill University","graduation_year":2016}]'
),
(
  'debcc7b5-850d-5b46-bfa9-8af18263c027',
  'Mason Rhodes',
  31,
  'mason.rhodes@example.com',
  '$2a$10$exampleMasonRhodes',
  'Machine Learning Engineer',
  'Los Angeles, CA',
  'Open to LMIA / O-1',
  7.5,
  205000,
  CURRENT_DATE + INTERVAL '60 days',
  'Python, PyTorch, LLMOps, Feature Stores, Airflow',
  NULL,
  NULL,
  'Launched multilingual retrieval system; built realtime experimentation platform',
  '[{"title":"Data Scientist","org":"Nimbus AI","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"MSc Applied Math","school":"University of Toronto","graduation_year":2017}]'
),
(
  'da667bc3-c7ce-5c1c-8a8a-3c4c29a554ef',
  'Mason Nakamura',
  32,
  'mason.nakamura@example.com',
  '$2a$10$exampleMasonNakamura',
  'Platform Engineer',
  'Denver, CO',
  'US Citizen',
  11.0,
  220000,
  CURRENT_DATE + INTERVAL '75 days',
  'Rust, Kubernetes, Terraform, AWS, Observability',
  NULL,
  NULL,
  'Designed multi-region Kubernetes platform; reduced infra spend 18%',
  '[{"title":"Site Reliability Engineer","org":"Cloudforge","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Electrical Engineering","school":"Georgia Tech","graduation_year":2018}]'
),
(
  'fe7fc3b4-d956-5cba-8838-c099b6e9a393',
  'Mason Okafor',
  33,
  'mason.okafor@example.com',
  '$2a$10$exampleMasonOkafor',
  'Data Platform Engineer',
  'Chicago, IL',
  'Canadian PR, TN ready',
  8.0,
  190000,
  CURRENT_DATE + INTERVAL '90 days',
  'Scala, Spark, Delta Lake, dbt, Snowflake',
  NULL,
  'Certified Data Platform Engineer',
  'Migration to lakehouse architecture; built governance catalog',
  '[{"title":"Data Engineer","org":"Aurora Analytics","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Information Systems","school":"UBC","graduation_year":2019}]'
),
(
  '9b7ccd13-2fa8-537d-a4ff-aea2f5bf3cf8',
  'Mason Hernandez',
  34,
  'mason.hernandez@example.com',
  '$2a$10$exampleMasonHernandez',
  'Security Engineer',
  'Boston, MA',
  'US Green Card',
  9.5,
  190000,
  CURRENT_DATE + INTERVAL '105 days',
  'AppSec, Threat Modeling, Node.js, Python, AWS',
  'Recognized for Security Engineer excellence',
  NULL,
  'Implemented SDL program; automated dependency scanning for 400 repos',
  '[{"title":"Security Analyst","org":"ShieldWorks","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Cybersecurity","school":"Carnegie Mellon","graduation_year":2012}]'
),
(
  '8851da08-f803-538e-bc34-ef9c267782d8',
  'Mason Liu',
  35,
  'mason.liu@example.com',
  '$2a$10$exampleMasonLiu',
  'Product Designer',
  'London, UK',
  'UK Skilled Worker',
  7.0,
  140000,
  CURRENT_DATE + INTERVAL '120 days',
  'Figma, Prototyping, Motion, Accessibility, Research',
  NULL,
  NULL,
  'Led end-to-end redesign of telehealth onboarding + design tokens library',
  '[{"title":"UX Designer","org":"Aether Health","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BA Interaction Design","school":"Goldsmiths","graduation_year":2013}]'
),
(
  '65aedcdc-3fe8-5826-a0eb-9fba35e08b7b',
  'Lena Patel',
  36,
  'lena.patel@example.com',
  '$2a$10$exampleLenaPatel',
  'Full Stack Engineer',
  'Berlin, DE',
  'Canadian Citizen',
  7.0,
  175000,
  CURRENT_DATE + INTERVAL '14 days',
  'Node.js, React, GraphQL, PostgreSQL, Tailwind',
  NULL,
  'Certified Full Stack Engineer',
  'Shipped multi-tenant analytics platform; maintained component library',
  '[{"title":"Software Engineer","org":"Vector Labs","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BASc Computer Engineering","school":"University of Toronto","graduation_year":2014}]'
),
(
  'e6cf5c23-d40b-5150-ae92-2ab64e00364d',
  'Lena Rhodes',
  37,
  'lena.rhodes@example.com',
  '$2a$10$exampleLenaRhodes',
  'Mobile Engineer',
  'Sydney, AU',
  'Australian PR',
  8.5,
  187000,
  CURRENT_DATE + INTERVAL '21 days',
  'React Native, Swift, Kotlin, GraphQL, CI/CD',
  NULL,
  NULL,
  'Built offline-first field app; introduced modular monorepo',
  '[{"title":"Mobile Developer","org":"Southern Apps","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"UNSW","graduation_year":2015}]'
),
(
  '57f1004c-8063-5e29-81f6-997c484e2e84',
  'Lena Nakamura',
  28,
  'lena.nakamura@example.com',
  '$2a$10$exampleLenaNakamura',
  'DevRel Engineer',
  'Melbourne, AU',
  'EU Blue Card',
  9.0,
  160000,
  CURRENT_DATE + INTERVAL '30 days',
  'Typescript, Docs-as-Code, Workshops, Content Strategy',
  'Recognized for DevRel Engineer excellence',
  NULL,
  'Grew developer community 3x; launched SDK reference apps',
  '[{"title":"Developer Advocate","org":"Polaris Cloud","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"Trinity College Dublin","graduation_year":2016}]'
),
(
  'a2f4ec49-0ff1-56a7-b0ed-6f55a1068c11',
  'Lena Okafor',
  29,
  'lena.okafor@example.com',
  '$2a$10$exampleLenaOkafor',
  'AI Product Manager',
  'Singapore',
  'US Citizen',
  9.0,
  205000,
  CURRENT_DATE + INTERVAL '45 days',
  'Roadmapping, Experiment Design, SQL, Python, Prompt Engineering',
  NULL,
  'Certified AI Product Manager',
  'Launched LLM-powered support agent reducing backlog 40%',
  '[{"title":"Product Manager","org":"Signal North","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"MBA","school":"MIT Sloan","graduation_year":2017}]'
),
(
  '238a93e7-aaa4-5d05-9216-1a5a474851aa',
  'Lena Hernandez',
  30,
  'lena.hernandez@example.com',
  '$2a$10$exampleLenaHernandez',
  'Senior Backend Engineer',
  'Tokyo, JP',
  'TN eligible',
  9.5,
  195000,
  CURRENT_DATE + INTERVAL '60 days',
  'Go, GraphQL, PostgreSQL, Kafka, Distributed systems',
  NULL,
  NULL,
  'Led payments rewrite for 5M users; built event-driven notification service',
  '[{"title":"Backend Engineer","org":"Northwind Systems","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"University of Waterloo","graduation_year":2018}]'
),
(
  '44a08630-c2ea-5360-98e3-a8d0ed90af58',
  'Lena Liu',
  31,
  'lena.liu@example.com',
  '$2a$10$exampleLenaLiu',
  'Staff Frontend Engineer',
  'Dublin, IE',
  'Canadian PR',
  9.0,
  195000,
  CURRENT_DATE + INTERVAL '75 days',
  'React, TypeScript, Next.js, GraphQL, Design Systems',
  NULL,
  NULL,
  'Scaled design system adoption across 8 squads; implemented SSR streaming UI',
  '[{"title":"Frontend Engineer","org":"Helios Labs","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Software Engineering","school":"McGill University","graduation_year":2019}]'
),
(
  'f430d6c7-ba3e-5dad-8845-1a683caad2d7',
  'Noah Patel',
  32,
  'noah.patel@example.com',
  '$2a$10$exampleNoahPatel',
  'Machine Learning Engineer',
  'Lisbon, PT',
  'Open to LMIA / O-1',
  7.0,
  200000,
  CURRENT_DATE + INTERVAL '90 days',
  'Python, PyTorch, LLMOps, Feature Stores, Airflow',
  'Recognized for Machine Learning Engineer excellence',
  'Certified Machine Learning Engineer',
  'Launched multilingual retrieval system; built realtime experimentation platform',
  '[{"title":"Data Scientist","org":"Nimbus AI","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"MSc Applied Math","school":"University of Toronto","graduation_year":2012}]'
),
(
  'f6887948-e01c-58c0-adb9-1cc570e7b022',
  'Noah Rhodes',
  33,
  'noah.rhodes@example.com',
  '$2a$10$exampleNoahRhodes',
  'Platform Engineer',
  'Barcelona, ES',
  'US Citizen',
  10.5,
  215000,
  CURRENT_DATE + INTERVAL '105 days',
  'Rust, Kubernetes, Terraform, AWS, Observability',
  NULL,
  NULL,
  'Designed multi-region Kubernetes platform; reduced infra spend 18%',
  '[{"title":"Site Reliability Engineer","org":"Cloudforge","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Electrical Engineering","school":"Georgia Tech","graduation_year":2013}]'
),
(
  '345dc9a0-be0b-54cb-9c78-ff6b2e95eba8',
  'Noah Nakamura',
  34,
  'noah.nakamura@example.com',
  '$2a$10$exampleNoahNakamura',
  'Data Platform Engineer',
  'Stockholm, SE',
  'Canadian PR, TN ready',
  9.0,
  185000,
  CURRENT_DATE + INTERVAL '120 days',
  'Scala, Spark, Delta Lake, dbt, Snowflake',
  NULL,
  NULL,
  'Migration to lakehouse architecture; built governance catalog',
  '[{"title":"Data Engineer","org":"Aurora Analytics","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Information Systems","school":"UBC","graduation_year":2014}]'
),
(
  '60f2cef5-8f47-5db3-ab31-6fcb768b5048',
  'Noah Okafor',
  35,
  'noah.okafor@example.com',
  '$2a$10$exampleNoahOkafor',
  'Security Engineer',
  'Auckland, NZ',
  'US Green Card',
  9.0,
  205000,
  CURRENT_DATE + INTERVAL '14 days',
  'AppSec, Threat Modeling, Node.js, Python, AWS',
  NULL,
  'Certified Security Engineer',
  'Implemented SDL program; automated dependency scanning for 400 repos',
  '[{"title":"Security Analyst","org":"ShieldWorks","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Cybersecurity","school":"Carnegie Mellon","graduation_year":2015}]'
),
(
  'ffafb67a-6833-572c-b639-72c58470e6fe',
  'Noah Hernandez',
  36,
  'noah.hernandez@example.com',
  '$2a$10$exampleNoahHernandez',
  'Product Designer',
  'Bangalore, IN',
  'UK Skilled Worker',
  6.5,
  135000,
  CURRENT_DATE + INTERVAL '21 days',
  'Figma, Prototyping, Motion, Accessibility, Research',
  'Recognized for Product Designer excellence',
  NULL,
  'Led end-to-end redesign of telehealth onboarding + design tokens library',
  '[{"title":"UX Designer","org":"Aether Health","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BA Interaction Design","school":"Goldsmiths","graduation_year":2016}]'
),
(
  '4d277134-ec6a-5ffd-86cc-728c8e97935d',
  'Noah Liu',
  37,
  'noah.liu@example.com',
  '$2a$10$exampleNoahLiu',
  'Full Stack Engineer',
  'Hyderabad, IN',
  'Canadian Citizen',
  8.0,
  170000,
  CURRENT_DATE + INTERVAL '30 days',
  'Node.js, React, GraphQL, PostgreSQL, Tailwind',
  NULL,
  NULL,
  'Shipped multi-tenant analytics platform; maintained component library',
  '[{"title":"Software Engineer","org":"Vector Labs","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BASc Computer Engineering","school":"University of Toronto","graduation_year":2017}]'
),
(
  'ed6d1f1d-2bdb-5d38-b89e-4c3c542cdcec',
  'Sofia Patel',
  28,
  'sofia.patel@example.com',
  '$2a$10$exampleSofiaPatel',
  'Mobile Engineer',
  'Mexico City, MX',
  'Australian PR',
  8.0,
  182000,
  CURRENT_DATE + INTERVAL '45 days',
  'React Native, Swift, Kotlin, GraphQL, CI/CD',
  NULL,
  'Certified Mobile Engineer',
  'Built offline-first field app; introduced modular monorepo',
  '[{"title":"Mobile Developer","org":"Southern Apps","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"UNSW","graduation_year":2018}]'
),
(
  '6fb976b1-8bf3-5060-a4f7-c4ba95b59ffa',
  'Sofia Rhodes',
  29,
  'sofia.rhodes@example.com',
  '$2a$10$exampleSofiaRhodes',
  'DevRel Engineer',
  'São Paulo, BR',
  'EU Blue Card',
  8.5,
  175000,
  CURRENT_DATE + INTERVAL '60 days',
  'Typescript, Docs-as-Code, Workshops, Content Strategy',
  NULL,
  NULL,
  'Grew developer community 3x; launched SDK reference apps',
  '[{"title":"Developer Advocate","org":"Polaris Cloud","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"Trinity College Dublin","graduation_year":2019}]'
),
(
  'acf4ddc5-96ee-5469-8376-40a0441c4461',
  'Sofia Nakamura',
  30,
  'sofia.nakamura@example.com',
  '$2a$10$exampleSofiaNakamura',
  'AI Product Manager',
  'Buenos Aires, AR',
  'US Citizen',
  10.0,
  200000,
  CURRENT_DATE + INTERVAL '75 days',
  'Roadmapping, Experiment Design, SQL, Python, Prompt Engineering',
  'Recognized for AI Product Manager excellence',
  NULL,
  'Launched LLM-powered support agent reducing backlog 40%',
  '[{"title":"Product Manager","org":"Signal North","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"MBA","school":"MIT Sloan","graduation_year":2012}]'
),
(
  '4d4acb0c-dfbe-527e-a28f-6083cc05f6e3',
  'Sofia Okafor',
  31,
  'sofia.okafor@example.com',
  '$2a$10$exampleSofiaOkafor',
  'Senior Backend Engineer',
  'Cape Town, ZA',
  'TN eligible',
  9.0,
  190000,
  CURRENT_DATE + INTERVAL '90 days',
  'Go, GraphQL, PostgreSQL, Kafka, Distributed systems',
  NULL,
  'Certified Senior Backend Engineer',
  'Led payments rewrite for 5M users; built event-driven notification service',
  '[{"title":"Backend Engineer","org":"Northwind Systems","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"University of Waterloo","graduation_year":2013}]'
),
(
  'ee0270b0-ea01-5ccb-a5a8-45724e28f581',
  'Sofia Hernandez',
  32,
  'sofia.hernandez@example.com',
  '$2a$10$exampleSofiaHernandez',
  'Staff Frontend Engineer',
  'Nairobi, KE',
  'Canadian PR',
  8.5,
  190000,
  CURRENT_DATE + INTERVAL '105 days',
  'React, TypeScript, Next.js, GraphQL, Design Systems',
  NULL,
  NULL,
  'Scaled design system adoption across 8 squads; implemented SSR streaming UI',
  '[{"title":"Frontend Engineer","org":"Helios Labs","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Software Engineering","school":"McGill University","graduation_year":2014}]'
),
(
  '8929800b-106d-55d4-b7d6-ad1b1cc78f43',
  'Sofia Liu',
  33,
  'sofia.liu@example.com',
  '$2a$10$exampleSofiaLiu',
  'Machine Learning Engineer',
  'Dubai, UAE',
  'Open to LMIA / O-1',
  8.0,
  215000,
  CURRENT_DATE + INTERVAL '120 days',
  'Python, PyTorch, LLMOps, Feature Stores, Airflow',
  NULL,
  NULL,
  'Launched multilingual retrieval system; built realtime experimentation platform',
  '[{"title":"Data Scientist","org":"Nimbus AI","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"MSc Applied Math","school":"University of Toronto","graduation_year":2015}]'
),
(
  '6de668cc-3475-5ff9-83c2-19fa9699f22d',
  'Eli Patel',
  34,
  'eli.patel@example.com',
  '$2a$10$exampleEliPatel',
  'Platform Engineer',
  'Warsaw, PL',
  'US Citizen',
  10.0,
  210000,
  CURRENT_DATE + INTERVAL '14 days',
  'Rust, Kubernetes, Terraform, AWS, Observability',
  'Recognized for Platform Engineer excellence',
  'Certified Platform Engineer',
  'Designed multi-region Kubernetes platform; reduced infra spend 18%',
  '[{"title":"Site Reliability Engineer","org":"Cloudforge","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Electrical Engineering","school":"Georgia Tech","graduation_year":2016}]'
),
(
  '397c66a5-8869-5e7f-b76b-12e768b09592',
  'Eli Rhodes',
  35,
  'eli.rhodes@example.com',
  '$2a$10$exampleEliRhodes',
  'Data Platform Engineer',
  'Prague, CZ',
  'Canadian PR, TN ready',
  8.5,
  180000,
  CURRENT_DATE + INTERVAL '21 days',
  'Scala, Spark, Delta Lake, dbt, Snowflake',
  NULL,
  NULL,
  'Migration to lakehouse architecture; built governance catalog',
  '[{"title":"Data Engineer","org":"Aurora Analytics","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Information Systems","school":"UBC","graduation_year":2017}]'
),
(
  'b5f49e92-377c-5b12-b016-8cfd053b74fe',
  'Eli Nakamura',
  36,
  'eli.nakamura@example.com',
  '$2a$10$exampleEliNakamura',
  'Security Engineer',
  'Zurich, CH',
  'US Green Card',
  10.0,
  200000,
  CURRENT_DATE + INTERVAL '30 days',
  'AppSec, Threat Modeling, Node.js, Python, AWS',
  NULL,
  NULL,
  'Implemented SDL program; automated dependency scanning for 400 repos',
  '[{"title":"Security Analyst","org":"ShieldWorks","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Cybersecurity","school":"Carnegie Mellon","graduation_year":2018}]'
),
(
  'a1bfc9a8-a1c5-56e2-b9bb-110705c960f0',
  'Eli Okafor',
  37,
  'eli.okafor@example.com',
  '$2a$10$exampleEliOkafor',
  'Product Designer',
  'Helsinki, FI',
  'UK Skilled Worker',
  6.0,
  150000,
  CURRENT_DATE + INTERVAL '45 days',
  'Figma, Prototyping, Motion, Accessibility, Research',
  NULL,
  'Certified Product Designer',
  'Led end-to-end redesign of telehealth onboarding + design tokens library',
  '[{"title":"UX Designer","org":"Aether Health","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BA Interaction Design","school":"Goldsmiths","graduation_year":2019}]'
),
(
  '403b1214-6b0a-595f-8d64-4677c5bb1978',
  'Eli Hernandez',
  28,
  'eli.hernandez@example.com',
  '$2a$10$exampleEliHernandez',
  'Full Stack Engineer',
  'Copenhagen, DK',
  'Canadian Citizen',
  7.5,
  165000,
  CURRENT_DATE + INTERVAL '60 days',
  'Node.js, React, GraphQL, PostgreSQL, Tailwind',
  'Recognized for Full Stack Engineer excellence',
  NULL,
  'Shipped multi-tenant analytics platform; maintained component library',
  '[{"title":"Software Engineer","org":"Vector Labs","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BASc Computer Engineering","school":"University of Toronto","graduation_year":2012}]'
),
(
  'bac80fc4-0968-5fdd-9b84-aa62c367a6ea',
  'Eli Liu',
  29,
  'eli.liu@example.com',
  '$2a$10$exampleEliLiu',
  'Mobile Engineer',
  'Oslo, NO',
  'Australian PR',
  9.0,
  177000,
  CURRENT_DATE + INTERVAL '75 days',
  'React Native, Swift, Kotlin, GraphQL, CI/CD',
  NULL,
  NULL,
  'Built offline-first field app; introduced modular monorepo',
  '[{"title":"Mobile Developer","org":"Southern Apps","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"UNSW","graduation_year":2013}]'
),
(
  '64b2b375-2bbd-584e-aaf3-b5d8fd06eb62',
  'Priya Patel',
  30,
  'priya.patel@example.com',
  '$2a$10$examplePriyaPatel',
  'DevRel Engineer',
  'Reykjavik, IS',
  'EU Blue Card',
  8.0,
  170000,
  CURRENT_DATE + INTERVAL '90 days',
  'Typescript, Docs-as-Code, Workshops, Content Strategy',
  NULL,
  'Certified DevRel Engineer',
  'Grew developer community 3x; launched SDK reference apps',
  '[{"title":"Developer Advocate","org":"Polaris Cloud","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"Trinity College Dublin","graduation_year":2014}]'
),
(
  'cc78be21-4734-58ba-a73f-5665c959fb90',
  'Priya Rhodes',
  31,
  'priya.rhodes@example.com',
  '$2a$10$examplePriyaRhodes',
  'AI Product Manager',
  'Madrid, ES',
  'US Citizen',
  9.5,
  215000,
  CURRENT_DATE + INTERVAL '105 days',
  'Roadmapping, Experiment Design, SQL, Python, Prompt Engineering',
  NULL,
  NULL,
  'Launched LLM-powered support agent reducing backlog 40%',
  '[{"title":"Product Manager","org":"Signal North","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"MBA","school":"MIT Sloan","graduation_year":2015}]'
),
(
  'd895ab0a-03fc-5614-9625-c619fb1e7f46',
  'Priya Nakamura',
  32,
  'priya.nakamura@example.com',
  '$2a$10$examplePriyaNakamura',
  'Senior Backend Engineer',
  'Rome, IT',
  'TN eligible',
  10.0,
  185000,
  CURRENT_DATE + INTERVAL '120 days',
  'Go, GraphQL, PostgreSQL, Kafka, Distributed systems',
  'Recognized for Senior Backend Engineer excellence',
  NULL,
  'Led payments rewrite for 5M users; built event-driven notification service',
  '[{"title":"Backend Engineer","org":"Northwind Systems","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"University of Waterloo","graduation_year":2016}]'
),
(
  'e104cb91-d013-5840-9a7f-a20b7b3eeafb',
  'Priya Okafor',
  33,
  'priya.okafor@example.com',
  '$2a$10$examplePriyaOkafor',
  'Staff Frontend Engineer',
  'Paris, FR',
  'Canadian PR',
  8.0,
  185000,
  CURRENT_DATE + INTERVAL '14 days',
  'React, TypeScript, Next.js, GraphQL, Design Systems',
  NULL,
  'Certified Staff Frontend Engineer',
  'Scaled design system adoption across 8 squads; implemented SSR streaming UI',
  '[{"title":"Frontend Engineer","org":"Helios Labs","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Software Engineering","school":"McGill University","graduation_year":2017}]'
),
(
  '7540546f-ba7f-5d3a-a1e1-3e9ef3c9081c',
  'Priya Hernandez',
  34,
  'priya.hernandez@example.com',
  '$2a$10$examplePriyaHernandez',
  'Machine Learning Engineer',
  'Amsterdam, NL',
  'Open to LMIA / O-1',
  7.5,
  210000,
  CURRENT_DATE + INTERVAL '21 days',
  'Python, PyTorch, LLMOps, Feature Stores, Airflow',
  NULL,
  NULL,
  'Launched multilingual retrieval system; built realtime experimentation platform',
  '[{"title":"Data Scientist","org":"Nimbus AI","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"MSc Applied Math","school":"University of Toronto","graduation_year":2018}]'
),
(
  '1f77ed31-1e25-56f3-9f4b-9f3179e1f2aa',
  'Priya Liu',
  35,
  'priya.liu@example.com',
  '$2a$10$examplePriyaLiu',
  'Platform Engineer',
  'Brussels, BE',
  'US Citizen',
  11.0,
  225000,
  CURRENT_DATE + INTERVAL '30 days',
  'Rust, Kubernetes, Terraform, AWS, Observability',
  NULL,
  NULL,
  'Designed multi-region Kubernetes platform; reduced infra spend 18%',
  '[{"title":"Site Reliability Engineer","org":"Cloudforge","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Electrical Engineering","school":"Georgia Tech","graduation_year":2019}]'
),
(
  '247dedf8-12a6-587d-9e6c-dc443a2dabb8',
  'Diego Patel',
  36,
  'diego.patel@example.com',
  '$2a$10$exampleDiegoPatel',
  'Data Platform Engineer',
  'Munich, DE',
  'Canadian PR, TN ready',
  8.0,
  175000,
  CURRENT_DATE + INTERVAL '45 days',
  'Scala, Spark, Delta Lake, dbt, Snowflake',
  'Recognized for Data Platform Engineer excellence',
  'Certified Data Platform Engineer',
  'Migration to lakehouse architecture; built governance catalog',
  '[{"title":"Data Engineer","org":"Aurora Analytics","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Information Systems","school":"UBC","graduation_year":2012}]'
),
(
  'd261a44b-6caf-59b6-9766-284e0c2a6b6b',
  'Diego Rhodes',
  37,
  'diego.rhodes@example.com',
  '$2a$10$exampleDiegoRhodes',
  'Security Engineer',
  'Vienna, AT',
  'US Green Card',
  9.5,
  195000,
  CURRENT_DATE + INTERVAL '60 days',
  'AppSec, Threat Modeling, Node.js, Python, AWS',
  NULL,
  NULL,
  'Implemented SDL program; automated dependency scanning for 400 repos',
  '[{"title":"Security Analyst","org":"ShieldWorks","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Cybersecurity","school":"Carnegie Mellon","graduation_year":2013}]'
),
(
  'f1ffe6aa-12e7-5f3c-93b2-7571b5df7f04',
  'Diego Nakamura',
  28,
  'diego.nakamura@example.com',
  '$2a$10$exampleDiegoNakamura',
  'Product Designer',
  'Tel Aviv, IL',
  'UK Skilled Worker',
  7.0,
  145000,
  CURRENT_DATE + INTERVAL '75 days',
  'Figma, Prototyping, Motion, Accessibility, Research',
  NULL,
  NULL,
  'Led end-to-end redesign of telehealth onboarding + design tokens library',
  '[{"title":"UX Designer","org":"Aether Health","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BA Interaction Design","school":"Goldsmiths","graduation_year":2014}]'
),
(
  '019c0e73-acdb-51e0-8b03-113202479c39',
  'Diego Okafor',
  29,
  'diego.okafor@example.com',
  '$2a$10$exampleDiegoOkafor',
  'Full Stack Engineer',
  'Doha, QA',
  'Canadian Citizen',
  7.0,
  180000,
  CURRENT_DATE + INTERVAL '90 days',
  'Node.js, React, GraphQL, PostgreSQL, Tailwind',
  NULL,
  'Certified Full Stack Engineer',
  'Shipped multi-tenant analytics platform; maintained component library',
  '[{"title":"Software Engineer","org":"Vector Labs","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BASc Computer Engineering","school":"University of Toronto","graduation_year":2015}]'
),
(
  'd61267f0-fb53-5b33-970f-55b66f73803b',
  'Diego Hernandez',
  30,
  'diego.hernandez@example.com',
  '$2a$10$exampleDiegoHernandez',
  'Mobile Engineer',
  'Hong Kong',
  'Australian PR',
  8.5,
  172000,
  CURRENT_DATE + INTERVAL '105 days',
  'React Native, Swift, Kotlin, GraphQL, CI/CD',
  'Recognized for Mobile Engineer excellence',
  NULL,
  'Built offline-first field app; introduced modular monorepo',
  '[{"title":"Mobile Developer","org":"Southern Apps","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"UNSW","graduation_year":2016}]'
),
(
  '85399145-dfd8-5b54-8557-64d1e221a6d3',
  'Diego Liu',
  31,
  'diego.liu@example.com',
  '$2a$10$exampleDiegoLiu',
  'DevRel Engineer',
  'Seoul, KR',
  'EU Blue Card',
  9.0,
  165000,
  CURRENT_DATE + INTERVAL '120 days',
  'Typescript, Docs-as-Code, Workshops, Content Strategy',
  NULL,
  NULL,
  'Grew developer community 3x; launched SDK reference apps',
  '[{"title":"Developer Advocate","org":"Polaris Cloud","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"Trinity College Dublin","graduation_year":2017}]'
),
(
  'ef3c5723-fd50-528b-80e2-6c38ddd53cc1',
  'Mina Patel',
  32,
  'mina.patel@example.com',
  '$2a$10$exampleMinaPatel',
  'AI Product Manager',
  'Taipei, TW',
  'US Citizen',
  9.0,
  210000,
  CURRENT_DATE + INTERVAL '14 days',
  'Roadmapping, Experiment Design, SQL, Python, Prompt Engineering',
  NULL,
  'Certified AI Product Manager',
  'Launched LLM-powered support agent reducing backlog 40%',
  '[{"title":"Product Manager","org":"Signal North","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"MBA","school":"MIT Sloan","graduation_year":2018}]'
),
(
  '64be175b-ddab-5f28-b224-7d6bf0b4eef6',
  'Mina Rhodes',
  33,
  'mina.rhodes@example.com',
  '$2a$10$exampleMinaRhodes',
  'Senior Backend Engineer',
  'Kuala Lumpur, MY',
  'TN eligible',
  9.5,
  200000,
  CURRENT_DATE + INTERVAL '21 days',
  'Go, GraphQL, PostgreSQL, Kafka, Distributed systems',
  NULL,
  NULL,
  'Led payments rewrite for 5M users; built event-driven notification service',
  '[{"title":"Backend Engineer","org":"Northwind Systems","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Computer Science","school":"University of Waterloo","graduation_year":2019}]'
),
(
  '2506a2da-f14c-5604-bbd1-3ed8bf83a557',
  'Mina Nakamura',
  34,
  'mina.nakamura@example.com',
  '$2a$10$exampleMinaNakamura',
  'Staff Frontend Engineer',
  'Jakarta, ID',
  'Canadian PR',
  9.0,
  180000,
  CURRENT_DATE + INTERVAL '30 days',
  'React, TypeScript, Next.js, GraphQL, Design Systems',
  'Recognized for Staff Frontend Engineer excellence',
  NULL,
  'Scaled design system adoption across 8 squads; implemented SSR streaming UI',
  '[{"title":"Frontend Engineer","org":"Helios Labs","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Software Engineering","school":"McGill University","graduation_year":2012}]'
),
(
  '6e682f6a-72f8-50b9-8b6d-75c4f19ed8e7',
  'Mina Okafor',
  35,
  'mina.okafor@example.com',
  '$2a$10$exampleMinaOkafor',
  'Machine Learning Engineer',
  'Istanbul, TR',
  'Open to LMIA / O-1',
  7.0,
  205000,
  CURRENT_DATE + INTERVAL '45 days',
  'Python, PyTorch, LLMOps, Feature Stores, Airflow',
  NULL,
  'Certified Machine Learning Engineer',
  'Launched multilingual retrieval system; built realtime experimentation platform',
  '[{"title":"Data Scientist","org":"Nimbus AI","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"MSc Applied Math","school":"University of Toronto","graduation_year":2013}]'
),
(
  'ec83e2dd-a9bf-5398-8c2c-dafc684d247a',
  'Mina Hernandez',
  36,
  'mina.hernandez@example.com',
  '$2a$10$exampleMinaHernandez',
  'Platform Engineer',
  'Austin, TX',
  'US Citizen',
  10.5,
  220000,
  CURRENT_DATE + INTERVAL '60 days',
  'Rust, Kubernetes, Terraform, AWS, Observability',
  NULL,
  NULL,
  'Designed multi-region Kubernetes platform; reduced infra spend 18%',
  '[{"title":"Site Reliability Engineer","org":"Cloudforge","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Electrical Engineering","school":"Georgia Tech","graduation_year":2014}]'
),
(
  '95253e2e-589d-5e6a-8853-44866411780a',
  'Mina Liu',
  37,
  'mina.liu@example.com',
  '$2a$10$exampleMinaLiu',
  'Data Platform Engineer',
  'Calgary, CA',
  'Canadian PR, TN ready',
  9.0,
  190000,
  CURRENT_DATE + INTERVAL '75 days',
  'Scala, Spark, Delta Lake, dbt, Snowflake',
  NULL,
  NULL,
  'Migration to lakehouse architecture; built governance catalog',
  '[{"title":"Data Engineer","org":"Aurora Analytics","start_date":"2018-01-01","end_date":"2022-06-01"}]',
  '[{"degree":"BSc Information Systems","school":"UBC","graduation_year":2015}]'
)
ON CONFLICT (candidate_id) DO NOTHING;
